 // Sample data
var feed_subscriptions_configuration = [
    { title: "Público", url: ("http://feeds.feedburner.com/publicoRSS"), content:'' },
    { title: "Jornal de Noticias", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: ''},
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' },
    { title: "Correio da Manhã", url: ("http://fastpshb.appspot.com/feed/1/fastpshb"), content: '' }
];